### ISSUE TITLE
Cannot use Java library with Java 8

### ISSUE THREAD

**Issue by phillipuniverse** [saucelabs/simple_sauce#178]
The prerequisites state that this can be used with a JDK8+ JVM:

https://github.com/saucelabs/sauce_bindings/blob/master/java/README.md#building

But, this jar is compiled with Java 9-only compatibility:

https://github.com/saucelabs/sauce_bindings/blob/da74978d20a7f9cb6e24cc7c6cfb38ec683db76b/java/pom.xml#L172-L179

Thus, when you attempt to add this dependency to another project targeting Java 8 (and specifically with a Java 8 JDK) you get this:

```console
Caused by: java.lang.UnsupportedClassVersionError: com/saucelabs/saucebindings/SauceSession has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
```

**Comment by titusfortner** [comment]
Yes, this package relies on some reflection features that are only available in Java 9 or above. At this time we do not have plans to refactor the code to support Java 8, but it isn't out of the question that we might revisit this decision in the future.

**Comment by phillipuniverse** [comment]
Cool, created https://github.com/saucelabs/sauce_bindings/pull/179 to fix the README.
